name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run prettier:ci
      - run: npm test
        env:
          CI: true
